### PR TITLE
the start to a rails server

### PR DESCRIPTION
**Pull request by nlavire**
this is just the start to the rails server more info in ReadMe

### CODE REVIEW

**Comment by swhcgh** [comment]
we really should get this into it's own repo instead of pulling into quadsolver

**Comment by bjclark13** [comment]
https://github.com/wmuCS4900Project/PalermoPOS

**Comment by bjclark13** [comment]
I think in order to pull this into the new repo, you'll first have to clone the new repo onto your local computer, move the source to that directory, and then push.

**Comment by swhcgh** [comment]
Fork the new repo to your own account first Nathan, and then you should be able to

git remote rm name
git remote add origin branchaddress
git commit -m 'init remote repo'
git push -u origin --all

This should force the remote to take the local files as the initial commit

**Pull request closed without merging**
