### PR TITLE
input slightly modified for error codes, test written, works great!

### PR DESCRIPTION
**Pull request by swhcgh**

### CODE REVIEW

**Comment by MatthewMazzarella** [comment]
So when I try to pull from git, It tells me to commit my changes. And when I try to commit changes it says there's an error with that branch. Can anyone else not pull?

**Comment by MatthewMazzarella** [comment]
screen shot 2016-11-15 at 5 58 01 pm

**Comment by bjclark13** [comment]
When you pulled before, it caused merge conflicts with your repo. Look at this documentation to resolve merge conflicts https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/ 

If that doesn't work, try `git merge --abort`

**Comment by MatthewMazzarella** [comment]
Thanks BJ, I'll look into it

**Review by bjclark13 — APPROVED** [review]

**Comment by MatthewMazzarella** [comment]
screen shot 2016-11-15 at 6 52 33 pm
I cannot see the .ds_store file otherwise I would be deleting it. Anyways, this is what happens. I seem to be getting more and more errors each time i abort and try pulling again.

**Comment by bjclark13** [comment]
All of the unmerge paths, go into the file and look for lines that look like `<<<<<<HEAD` and `>>>>>>>>>` and `========`. These show that there are merge conflicts. Fix those conflicts, by deleting the sections that aren't supposed to be there. Once they are fixed, `git add` the file that you fixed. Also add the changes not staged for commit. Once those are all added, then you can `git commit`.

**Comment by MatthewMazzarella** [comment]
Okay, so I just pushed to origin master. But now I'm not able to create a new pull request. I have to do that before pulling from upstream master correct?

**Pull request merged**
